apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi-db
spec:
  replicas: 0
  selector:
    matchLabels:
      app: strapi-db
  template:
    metadata:
      labels:
        app: strapi-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: "strapi"
            - name: POSTGRES_PASSWORD
              value: "strapi"
            - name: POSTGRES_DB
              value: "strapi"
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: strapi-db
spec:
  selector:
    app: strapi-db
  ports:
    - port: 5432
      targetPort: 5432