apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  replicas: 10
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command:
            - sh
            - -c
            - |
              echo "Waiting for Postgres..."
              until nc -z strapi-db 5432; do
                echo "Postgres not ready, waiting..."
                sleep 2
              done
              echo "Postgres is up!"
      initContainers:
        - name: init-strapi-public
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /opt/app/public/uploads
              chmod -R 777 /opt/app/public
          volumeMounts:
            - name: strapi-storage
              mountPath: /opt/app/public      
      containers:
        - name: strapi
          image: lucianoalbis/teste-img-cms:v3
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_HOST
              value: "strapi-db"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "strapi"
            - name: DATABASE_USERNAME
              value: "strapi"
            - name: DATABASE_PASSWORD
              value: "strapi"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "1337"
            - name: STRAPI_ADMIN_BACKEND_URL
              value: "http://strapi:1337"
          volumeMounts:
            - name: strapi-storage
              mountPath: /opt/app/public
      volumes:
        - name: strapi-storage
          persistentVolumeClaim:
            claimName: strapi-pvc              
---
apiVersion: v1
kind: Service
metadata:
  name: strapi
spec:
  type: NodePort
  selector:
    app: strapi
  ports:
    - port: 1337
      targetPort: 1337
      nodePort: 31337

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: strapi-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany   # Permite múltiplos pods lerem e escreverem
  hostPath:
    path: /mnt/data/strapi   # Diretório do Minikube host
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi