apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          image: lucianoalbis/teste-img-cms:v2
          ports:
            - containerPort: 1337
          env:
            - name: DATABASE_CLIENT
              value: "postgres"
            - name: DATABASE_HOST
              value: "strapi-db"
            - name: DATABASE_PORT
              value: "5432"
            - name: DATABASE_NAME
              value: "strapi"
            - name: DATABASE_USERNAME
              value: "strapi"
            - name: DATABASE_PASSWORD
              value: "strapi"
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "1337"

---
apiVersion: v1
kind: Service
metadata:
  name: strapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 1337
  selector:
    app: strapi